# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: vodafone_api
    build: .
    command: gunicorn -b 0.0.0.0:5000 vodafone_api.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/vodafone_api.db
    volumes:
      - ./vodafone_api:/code/vodafone_api
      - ./db/:/db/
    ports:
      - "5000:5000"
